apiVersion: v1
kind: Pod
metadata: 
 name: label-demo
 labels:
  course: DevOps
  Trainer: "sivakumarReddy"
spec:
# list of containers
  containers:
  - name: hello-pod
    image: nginx
    ports:
    - containerport: 80   