apiVersion: v1
kind: pod
metadata:
  name: hello-pod
 # namespace: roboshop
spec: 
 # list of containers
  containers:
  - name: hello-pod
    image: nginx

# here with this line port will not be opened, just for information
    ports:
    - containerport: 80
    resources:
      requests:
        cpu: "100m"
        memory: "68mi"
      limits:
        cpu: "200m"
        memory: "128mi"


    
