# apiVersion: v1
# kind: Pod
# metadata: 
#   name: secret-pod
# spec:
#   containers:
#   - name: secret-pod 
#     image: nginx
#     ports:
#     - containerPort: 80
#     envFrom:
#     - secretRef:
#       name: devops-secret


apiVersion: v1
kind: Pod
metadata:
  name: secret-pod
spec:
  # list of containers
  containers:
  - name: secret-pod
    image: nginx
    #here with this line port will not be opened, just for information
    ports:
    - containerPort: 80
    envFrom:
    - secretRef:
        name: devops-secret